### PR TITLE
use gcr.io/distroless/base-debian11:nonroot image

### PR DESCRIPTION
**Pull request by TheDen**
PR to update the `Dockerfile` to use the [nonroot image](https://github.com/GoogleContainerTools/distroless#how-do-i-use-distroless-images)

### CODE REVIEW

**Comment by BradLewis** [comment]
What's the reason for this?

**Comment by TheDen** [comment]
> What's the reason for this?

* Container doesn't run as root
* We can remove the hadlont ignore rule

**Review by BradLewis — COMMENTED** [review]
Do you think we still need all this nonroot stuff given that we're using the nonroot image now?

**Comment by TheDen** [comment]
> Do you think we still need all this nonroot stuff given that we're using the nonroot image now?

I think it's needed for the `COPY --chown` since it's copied from a different stage, but not sure about `USER nonroot:nonroot` is needed.

**Review by BradLewis — APPROVED** [review]
LGTM

**Pull request merged**
